version: "3"

services:
  database:
    container_name: database
    image: postgres:alpine
    restart: on-failure
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $DATABASE
    networks:
      - botnet
    ports:
      - 5432:5432
    volumes:
      - .data/postgresql:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    volumes:
      - .data/redis:/var/lib/redis
    ports:
      - 6379:6379

  bot:
    container_name: bot
    build:
      context: .
    restart: on-failure
    command: python app.py
    networks:
      - botnet
    depends_on:
      - database
      - redis

networks:
  botnet:
    driver: bridge
